/**
 * PDF report renderer for the commission audit module.
 *
 * Uses jsPDF + jspdf-autotable to produce a multi-page, client-facing report:
 *   1. Cover page (Zed Automation branding, client, period, confidentiality note)
 *   2. Executive summary (KPI cards + plain-English narrative + key figures)
 *   3. Detailed findings table (every transaction, colour-coded by variance)
 *   4. Top 5 discrepancies with per-deal breakdowns
 *   5. Recommendations derived from the findings
 *   + footer with page numbers, "Generated by Zed Automation" and contact details
 *
 * This module is intentionally separate from `report-data.ts` so that the heavy
 * jsPDF/autotable bundle is only loaded when a user actually generates a report
 * (see the dynamic import in `PdfReportDialog`).
 */

import { jsPDF } from 'jspdf';
import { autoTable } from 'jspdf-autotable';

import { buildReportBundle, buildReportFileName } from '@/lib/commission-audit/report-data';
import type { ReportBundle, ReportOptions } from '@/lib/commission-audit/report-data';
import { calculateAudit } from '@/lib/commission-audit/audit';
import { formatMoney, formatPercent, formatSignedMoney } from '@/lib/commission-audit/format';
import type { AuditStatus, Transaction } from '@/types/commission-audit';

/* -------------------------------------------------------------------------- */
/*  Layout constants (millimetres, US Letter)                                 */
/* -------------------------------------------------------------------------- */

const PAGE_WIDTH = 215.9;
const PAGE_HEIGHT = 279.4;
const MARGIN = { left: 15, right: 15, top: 15, bottom: 22 };
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN.left - MARGIN.right;
const CONTENT_TOP = 38;
const CONTENT_BOTTOM = PAGE_HEIGHT - MARGIN.bottom;
const FOOTER_LINE_Y = PAGE_HEIGHT - 16;

type Rgb = [number, number, number];

const C = {
  white: [255, 255, 255] as Rgb,
  slate900: [15, 23, 42] as Rgb,
  slate800: [30, 41, 59] as Rgb,
  slate700: [51, 65, 85] as Rgb,
  slate600: [71, 85, 105] as Rgb,
  slate500: [100, 116, 139] as Rgb,
  slate400: [148, 163, 184] as Rgb,
  slate300: [203, 213, 225] as Rgb,
  slate200: [226, 232, 240] as Rgb,
  slate100: [241, 245, 249] as Rgb,
  slate50: [248, 250, 252] as Rgb,
  emerald700: [4, 120, 87] as Rgb,
  emerald600: [5, 150, 105] as Rgb,
  emerald50: [236, 253, 245] as Rgb,
  rose700: [190, 18, 60] as Rgb,
  rose600: [225, 29, 72] as Rgb,
  rose50: [255, 241, 242] as Rgb,
  amber700: [180, 83, 9] as Rgb,
  amber600: [217, 119, 6] as Rgb,
  amber50: [255, 251, 235] as Rgb,
  orange600: [234, 88, 12] as Rgb,
  orange50: [255, 247, 237] as Rgb,
} as const;

const STATUS_STYLE: Record<AuditStatus, { fill: Rgb; text: Rgb; label: string }> = {
  overpaid: { fill: C.rose50, text: C.rose700, label: 'Overpaid' },
  underpaid: { fill: C.amber50, text: C.amber700, label: 'Underpaid' },
  correct: { fill: C.slate50, text: C.slate600, label: 'Accurate' },
};

const FONT = 'helvetica';

/**
 * Show a deduction with a leading minus sign.
 * ASCII hyphen only — WinAnsi cannot encode U+2212, which renders as a quote.
 * Zero deductions render as "$0.00" rather than the ugly "-$0.00".
 */
function deduct(amount: number): string {
  return amount > 0.005 ? `-${formatMoney(amount)}` : formatMoney(0);
}

/* -------------------------------------------------------------------------- */
/*  Low-level drawing helpers                                                 */
/* -------------------------------------------------------------------------- */

function setFill(doc: jsPDF, rgb: Rgb): void {
  doc.setFillColor(rgb[0], rgb[1], rgb[2]);
}

function setStroke(doc: jsPDF, rgb: Rgb): void {
  doc.setDrawColor(rgb[0], rgb[1], rgb[2]);
}

function setText(doc: jsPDF, rgb: Rgb): void {
  doc.setTextColor(rgb[0], rgb[1], rgb[2]);
}

interface TextOptions {
  size?: number;
  bold?: boolean;
  color?: Rgb;
  align?: 'left' | 'center' | 'right';
  maxWidth?: number;
}

/** Draw a single line of text and return the y position of the next line. */
function drawText(doc: jsPDF, text: string, x: number, y: number, options: TextOptions = {}): number {
  const { size = 10, bold = false, color = C.slate700, align = 'left', maxWidth } = options;
  doc.setFont(FONT, bold ? 'bold' : 'normal');
  doc.setFontSize(size);
  setText(doc, color);
  doc.text(text, x, y, { align, maxWidth });
  return y + size * 0.42;
}

/** Draw a wrapped paragraph and return the y position below it. */
function drawParagraph(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  width: number,
  options: { size?: number; lineHeight?: number; bold?: boolean; color?: Rgb } = {},
): number {
  const { size = 9.5, lineHeight = 4.7, bold = false, color = C.slate700 } = options;
  doc.setFont(FONT, bold ? 'bold' : 'normal');
  doc.setFontSize(size);
  setText(doc, color);
  const lines = doc.splitTextToSize(text, width) as string[];
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

/** Text width in millimetres for the current font/size. */
function measure(doc: jsPDF, text: string, size: number, bold = false): number {
  doc.setFont(FONT, bold ? 'bold' : 'normal');
  doc.setFontSize(size);
  return doc.getTextWidth(text);
}

/** Number of lines `text` will occupy inside `width`. */
function lineCount(doc: jsPDF, text: string, width: number, size = 9.5): number {
  doc.setFont(FONT, 'normal');
  doc.setFontSize(size);
  return (doc.splitTextToSize(text, width) as string[]).length;
}

/** Rounded card with an optional accent border. */
function drawCard(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  height: number,
  options: { fill?: Rgb; border?: Rgb; radius?: number } = {},
): void {
  const { fill = C.white, border = C.slate200, radius = 2 } = options;
  setFill(doc, fill);
  setStroke(doc, border);
  doc.setLineWidth(0.25);
  doc.roundedRect(x, y, width, height, radius, radius, 'FD');
}

/** The small brand mark used in page headers and on the cover. */
function drawBrandMark(doc: jsPDF, x: number, y: number, size = 7): void {
  setFill(doc, C.emerald600);
  doc.roundedRect(x, y, size, size, 1.2, 1.2, 'F');
  doc.setFont(FONT, 'bold');
  doc.setFontSize(size * 0.95);
  setText(doc, C.white);
  doc.text('Z', x + size / 2, y + size * 0.72, { align: 'center' });
}

/** Compact running header used on every content page. */
function drawRunningHeader(doc: jsPDF, clientName: string): void {
  drawBrandMark(doc, MARGIN.left, MARGIN.top - 6);
  drawText(doc, 'ZED AUTOMATION', MARGIN.left + 10, MARGIN.top - 1, {
    size: 8,
    bold: true,
    color: C.slate500,
  });
  drawText(doc, `Commission Audit Report  ·  ${clientName}`, PAGE_WIDTH - MARGIN.right, MARGIN.top - 1, {
    size: 8,
    color: C.slate400,
    align: 'right',
  });
  setStroke(doc, C.slate200);
  doc.setLineWidth(0.3);
  doc.line(MARGIN.left, MARGIN.top + 2.5, PAGE_WIDTH - MARGIN.right, MARGIN.top + 2.5);
}

/** Section title block on a fresh content page. Returns the first usable y. */
function drawSectionTitle(doc: jsPDF, title: string, subtitle?: string): number {
  drawText(doc, title, MARGIN.left, CONTENT_TOP, { size: 17, bold: true, color: C.slate900 });
  let y = CONTENT_TOP + 6.5;
  if (subtitle) {
    y = drawParagraph(doc, subtitle, MARGIN.left, y, CONTENT_WIDTH, { size: 9, color: C.slate500 });
  }
  setFill(doc, C.emerald600);
  doc.rect(MARGIN.left, y + 0.5, 22, 1.1, 'F');
  return y + 8;
}

/** Page footer with page numbers, provenance and a contact placeholder. */
function drawFooters(doc: jsPDF, report: ReportBundle): void {
  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    setStroke(doc, C.slate200);
    doc.setLineWidth(0.3);
    doc.line(MARGIN.left, FOOTER_LINE_Y, PAGE_WIDTH - MARGIN.right, FOOTER_LINE_Y);

    drawText(doc, 'Generated by Zed Automation', MARGIN.left, FOOTER_LINE_Y + 4.5, {
      size: 7.5,
      color: C.slate400,
    });
    drawText(
      doc,
      `${report.contactEmail}  ·  ${report.contactPhone}`,
      PAGE_WIDTH / 2,
      FOOTER_LINE_Y + 4.5,
      { size: 7.5, color: C.slate400, align: 'center' },
    );
    drawText(doc, `Page ${page} of ${pageCount}`, PAGE_WIDTH - MARGIN.right, FOOTER_LINE_Y + 4.5, {
      size: 7.5,
      color: C.slate400,
      align: 'right',
    });
  }
}

/** `doc.lastAutoTable.finalY` with a safe fallback across plugin versions. */
function tableFinalY(doc: jsPDF, fallback: number): number {
  const withPlugin = doc as unknown as { lastAutoTable?: { finalY?: number } };
  if (typeof withPlugin.lastAutoTable?.finalY === 'number') {
    return withPlugin.lastAutoTable.finalY as number;
  }
  const getter = (doc as unknown as { getLastAutoTable?: () => { finalY?: number } | null })
    .getLastAutoTable;
  if (typeof getter === 'function') {
    const table = getter.call(doc);
    if (table && typeof table.finalY === 'number') return table.finalY;
  }
  return fallback;
}

/* -------------------------------------------------------------------------- */
/*  Page 1 — cover                                                            */
/* -------------------------------------------------------------------------- */

function drawCoverPage(doc: jsPDF, report: ReportBundle): void {
  const bandHeight = 68;

  // Brand band
  setFill(doc, C.slate900);
  doc.rect(0, 0, PAGE_WIDTH, bandHeight, 'F');
  setFill(doc, C.emerald600);
  doc.rect(0, bandHeight, PAGE_WIDTH, 1.6, 'F');

  drawBrandMark(doc, MARGIN.left, 20, 12);
  drawText(doc, 'ZED AUTOMATION', MARGIN.left + 17, 27, {
    size: 15,
    bold: true,
    color: C.white,
  });
  drawText(doc, 'Commission Audit & Leakage Detection', MARGIN.left + 17, 33.5, {
    size: 8.5,
    color: C.slate400,
  });

  // Confidentiality badge
  const badgeLabel = 'CONFIDENTIAL';
  const badgeWidth = measure(doc, badgeLabel, 7.5, true) + 8;
  setStroke(doc, C.emerald600);
  doc.setLineWidth(0.4);
  doc.roundedRect(PAGE_WIDTH - MARGIN.right - badgeWidth, 20, badgeWidth, 8, 1.5, 1.5, 'S');
  drawText(doc, badgeLabel, PAGE_WIDTH - MARGIN.right - badgeWidth / 2, 25.3, {
    size: 7.5,
    bold: true,
    color: C.emerald600,
    align: 'center',
  });

  // Title block
  drawText(doc, 'Commission Audit Report', MARGIN.left, 52, {
    size: 24,
    bold: true,
    color: C.white,
  });

  let y = 86;
  y = drawParagraph(
    doc,
    `Independent reconciliation of commission disbursements prepared exclusively for ${
      report.clientName
    }${report.company ? ` (${report.company})` : ''}.`,
    MARGIN.left,
    y,
    CONTENT_WIDTH,
    { size: 10.5, color: C.slate600, lineHeight: 5.2 },
  );

  setFill(doc, C.emerald600);
  doc.rect(MARGIN.left, y + 1, 26, 1.2, 'F');
  y += 12;

  // Metadata grid
  const metaRows: Array<[string, string]> = [
    ['Client', report.clientName],
    ...(report.company ? ([['Company', report.company]] as Array<[string, string]>) : []),
    ['Audit period', report.periodLabel],
    [
      'Report date',
      report.reportDateLabel,
    ],
    ['Prepared by', report.preparedBy],
    ['Transactions audited', String(report.summary.totalTransactions)],
    ['Sale volume audited', formatMoney(report.summary.totalSalePrice)],
    ['Gross commission audited', formatMoney(report.summary.totalCommission)],
  ];

  metaRows.forEach(([label, value], index) => {
    const rowY = y + index * 11;
    if (index % 2 === 0) {
      setFill(doc, C.slate50);
      doc.rect(MARGIN.left, rowY - 4.6, CONTENT_WIDTH, 10, 'F');
    }
    drawText(doc, label.toUpperCase(), MARGIN.left + 3, rowY, {
      size: 7.5,
      bold: true,
      color: C.slate500,
    });
    drawText(doc, value, MARGIN.left + 62, rowY + 0.4, {
      size: 10.5,
      color: C.slate900,
      maxWidth: CONTENT_WIDTH - 68,
    });
  });

  y += metaRows.length * 11 + 4;

  // Confidentiality note
  const noteTitle = 'CONFIDENTIALITY NOTE';
  const noteBody =
    `This report was prepared by Zed Automation for ${report.clientName} and contains confidential ` +
    'commission, compensation and referral data. It is intended solely for the named client and its ' +
    'authorized advisors. Figures are derived from the transaction records supplied to Zed Automation ' +
    'and are not an audited financial statement; they should be reconciled against settlement ' +
    "statements and the brokerage's disbursement ledger before any adjusting entry is posted. " +
    'Do not distribute outside your organisation without written consent from Zed Automation.';

  const noteLines = lineCount(doc, noteBody, CONTENT_WIDTH - 12, 8);
  const noteHeight = 14 + noteLines * 4.1;

  drawCard(doc, MARGIN.left, y, CONTENT_WIDTH, noteHeight, { fill: C.slate50, border: C.slate200 });
  drawText(doc, noteTitle, MARGIN.left + 6, y + 7, { size: 8, bold: true, color: C.rose600 });
  drawParagraph(doc, noteBody, MARGIN.left + 6, y + 13, CONTENT_WIDTH - 12, {
    size: 8,
    lineHeight: 4.1,
    color: C.slate600,
  });
}

/* -------------------------------------------------------------------------- */
/*  Page 2 — executive summary                                                */
/* -------------------------------------------------------------------------- */

interface KpiCard {
  label: string;
  value: string;
  caption: string;
  accent: Rgb;
  fill: Rgb;
}

function drawKpiCards(doc: jsPDF, cards: KpiCard[], x: number, y: number, width: number): number {
  const gap = 3.5;
  const cardWidth = (width - gap * (cards.length - 1)) / cards.length;
  const cardHeight = 27;

  cards.forEach((card, index) => {
    const cardX = x + index * (cardWidth + gap);
    drawCard(doc, cardX, y, cardWidth, cardHeight, { fill: card.fill, border: card.accent });

    drawText(doc, card.label.toUpperCase(), cardX + 3.5, y + 6.5, {
      size: 6.8,
      bold: true,
      color: card.accent,
      maxWidth: cardWidth - 7,
    });
    drawText(doc, card.value, cardX + 3.5, y + 15.5, {
      size: 13,
      bold: true,
      color: card.accent,
      maxWidth: cardWidth - 7,
    });
    drawParagraph(doc, card.caption, cardX + 3.5, y + 20.5, cardWidth - 7, {
      size: 6.5,
      lineHeight: 3.2,
      color: C.slate500,
    });
  });

  return y + cardHeight;
}

function drawExecutiveSummaryPage(doc: jsPDF, report: ReportBundle): void {
  doc.addPage();
  drawRunningHeader(doc, report.clientName);

  const { summary } = report;

  let y = drawSectionTitle(
    doc,
    'Executive Summary',
    `Performance for ${report.periodLabel} · prepared ${report.reportDateLabel}`,
  );

  y = drawKpiCards(
    doc,
    [
      {
        label: 'Transactions audited',
        value: String(summary.totalTransactions),
        caption: `${formatMoney(summary.totalSalePrice)} in sale volume`,
        accent: C.slate700,
        fill: C.white,
      },
      {
        label: 'Total overpaid',
        value: formatMoney(summary.totalOverpaid),
        caption: `${summary.overpaidCount} deal${summary.overpaidCount === 1 ? '' : 's'} disbursed above contract`,
        accent: C.rose600,
        fill: C.rose50,
      },
      {
        label: 'Total underpaid',
        value: formatMoney(summary.totalUnderpaid),
        caption: `${summary.underpaidCount} deal${summary.underpaidCount === 1 ? '' : 's'} still owed to agents`,
        accent: C.amber600,
        fill: C.amber50,
      },
      {
        label: 'Missing referral income',
        value: formatMoney(summary.totalMissingReferral),
        caption: `${summary.referralCount} deal${summary.referralCount === 1 ? '' : 's'} with uncollected fees`,
        accent: C.orange600,
        fill: C.orange50,
      },
    ],
    MARGIN.left,
    y,
    CONTENT_WIDTH,
  );

  y += 6;

  // Net discrepancy bar
  const net = summary.netDiscrepancy;
  const netStyle =
    net > 0.5
      ? { accent: C.rose600, fill: C.rose50, caption: 'Net brokerage leakage — recoverable overpayment' }
      : net < -0.5
        ? { accent: C.amber600, fill: C.amber50, caption: 'Net agent shortfall — payable to agents' }
        : { accent: C.emerald600, fill: C.emerald50, caption: 'Books balanced against contract' };

  const barHeight = 20;
  drawCard(doc, MARGIN.left, y, CONTENT_WIDTH, barHeight, {
    fill: netStyle.fill,
    border: netStyle.accent,
  });
  drawText(doc, 'NET DISCREPANCY', MARGIN.left + 5, y + 8, {
    size: 8,
    bold: true,
    color: netStyle.accent,
  });
  drawParagraph(doc, netStyle.caption, MARGIN.left + 5, y + 14, CONTENT_WIDTH * 0.62, {
    size: 7.5,
    lineHeight: 3.6,
    color: C.slate600,
  });
  drawText(doc, formatSignedMoney(net), PAGE_WIDTH - MARGIN.right - 5, y + 12, {
    size: 17,
    bold: true,
    color: netStyle.accent,
    align: 'right',
  });

  y += barHeight + 8;

  // Narrative
  drawText(doc, 'What this means', MARGIN.left, y, { size: 11, bold: true, color: C.slate900 });
  y += 5.5;
  y = drawParagraph(doc, report.executiveSummary, MARGIN.left, y, CONTENT_WIDTH, {
    size: 9.5,
    lineHeight: 4.9,
    color: C.slate700,
  });

  y += 7;

  // Key figures table
  if (y > CONTENT_BOTTOM - 60) {
    doc.addPage();
    drawRunningHeader(doc, report.clientName);
    y = CONTENT_TOP;
  }

  drawText(doc, 'Key figures', MARGIN.left, y, { size: 11, bold: true, color: C.slate900 });
  y += 3;

  const matchRate =
    summary.totalTransactions > 0
      ? formatPercent((summary.correctCount / summary.totalTransactions) * 100)
      : '0.0%';

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN.left, right: MARGIN.right, bottom: MARGIN.bottom },
    theme: 'grid',
    styles: { font: FONT, fontSize: 8.5, cellPadding: 2.2, textColor: C.slate700, lineColor: C.slate200, lineWidth: 0.2 },
    head: [['Metric', 'Amount']],
    body: [
      ['Sale volume audited', formatMoney(summary.totalSalePrice)],
      ['Gross commission generated', formatMoney(summary.totalCommission)],
      ['Brokerage commission retained', formatMoney(summary.totalBrokerageCut)],
      ['Expected agent payments', formatMoney(summary.totalExpectedAgentPayment)],
      ['Actual agent payments', formatMoney(summary.totalActualPaid)],
      ['Broker overpayments (recoverable)', formatMoney(summary.totalOverpaid)],
      ['Agent underpayments (payable)', formatMoney(summary.totalUnderpaid)],
      ['Outstanding incoming referral income', formatMoney(summary.totalMissingReferral)],
      ['Deals matching contract exactly', `${summary.correctCount} of ${summary.totalTransactions} (${matchRate})`],
    ],
    headStyles: { fillColor: C.slate900, textColor: C.white, fontStyle: 'bold', fontSize: 8 },
    columnStyles: {
      0: { cellWidth: CONTENT_WIDTH * 0.62 },
      1: { cellWidth: CONTENT_WIDTH * 0.38, halign: 'right', fontStyle: 'bold', textColor: C.slate900 },
    },
    alternateRowStyles: { fillColor: C.slate50 },
  });
}

/* -------------------------------------------------------------------------- */
/*  Page 3 — detailed findings                                                */
/* -------------------------------------------------------------------------- */

function drawFindingsPage(doc: jsPDF, report: ReportBundle, transactions: Transaction[]): void {
  doc.addPage();
  drawRunningHeader(doc, report.clientName);

  const { summary } = report;
  const y = drawSectionTitle(
    doc,
    'Detailed Findings',
    `All ${summary.totalTransactions} audited transaction${
      summary.totalTransactions === 1 ? '' : 's'
    }. Rows are color-coded: red = brokerage overpaid, yellow = brokerage underpaid.`,
  );

  const statuses = transactions.map((transaction) => calculateAudit(transaction).status);

  if (transactions.length === 0) {
    drawCard(doc, MARGIN.left, y, CONTENT_WIDTH, 22, { fill: C.slate50, border: C.slate200 });
    drawText(doc, 'No transactions to report', MARGIN.left + 5, y + 9, {
      size: 10,
      bold: true,
      color: C.slate700,
    });
    drawParagraph(
      doc,
      'Import a transaction export or add transactions manually, then generate this report again to see the detailed findings table.',
      MARGIN.left + 5,
      y + 15,
      CONTENT_WIDTH - 10,
      { size: 8.5, lineHeight: 3.8, color: C.slate600 },
    );
    return;
  }

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN.left, right: MARGIN.right, bottom: MARGIN.bottom },
    theme: 'grid',
    styles: {
      font: FONT,
      fontSize: 7,
      cellPadding: 1.8,
      textColor: C.slate700,
      lineColor: C.slate200,
      lineWidth: 0.15,
      valign: 'middle',
      overflow: 'linebreak',
    },
    head: [
      [
        'Property Address',
        'Sale Price',
        'Expected Agent Payment',
        'Actual Paid',
        'Discrepancy',
        'Status',
      ],
    ],
    body: transactions.map((transaction) => {
      const audit = calculateAudit(transaction);
      return [
        transaction.address || '(no address)',
        formatMoney(transaction.salePrice),
        formatMoney(audit.expectedAgentPayment),
        formatMoney(transaction.actualPaid),
        formatSignedMoney(audit.discrepancy),
        audit.statusText === 'Accurate' ? 'Accurate' : audit.statusText.replace('Broker ', ''),
      ];
    }),
    headStyles: {
      fillColor: C.slate900,
      textColor: C.white,
      fontStyle: 'bold',
      fontSize: 7,
      halign: 'left',
    },
    columnStyles: {
      0: { cellWidth: 50 },
      1: { cellWidth: 25, halign: 'right' },
      2: { cellWidth: 34, halign: 'right' },
      3: { cellWidth: 25, halign: 'right' },
      4: { cellWidth: 26, halign: 'right', fontStyle: 'bold' },
      5: { cellWidth: 25.9, halign: 'center', fontStyle: 'bold' },
    },
    didParseCell: (data) => {
      if (data.section !== 'body') return;
      const status = statuses[data.row.index] ?? 'correct';
      const style = STATUS_STYLE[status];
      data.cell.styles.fillColor = style.fill;
      if (data.column.index === 4 || data.column.index === 5) {
        data.cell.styles.textColor = style.text;
      }
    },
  });

  let y2 = tableFinalY(doc, y) + 6;

  if (y2 > CONTENT_BOTTOM - 18) {
    doc.addPage();
    drawRunningHeader(doc, report.clientName);
    y2 = CONTENT_TOP;
  }

  drawCard(doc, MARGIN.left, y2, CONTENT_WIDTH, 15, { fill: C.slate50, border: C.slate200 });
  drawText(doc, 'RECONCILIATION', MARGIN.left + 5, y2 + 6, {
    size: 7.5,
    bold: true,
    color: C.slate500,
  });
  drawParagraph(
    doc,
    `${summary.correctCount} deal${summary.correctCount === 1 ? '' : 's'} matched the contract exactly, ${summary.overpaidCount} were overpaid by ${formatMoney(
      summary.totalOverpaid,
    )} and ${summary.underpaidCount} were underpaid by ${formatMoney(summary.totalUnderpaid)}.`,
    MARGIN.left + 5,
    y2 + 11,
    CONTENT_WIDTH - 10,
    { size: 8, lineHeight: 3.6, color: C.slate600 },
  );
}

/* -------------------------------------------------------------------------- */
/*  Page 4 — top 5 discrepancies                                              */
/* -------------------------------------------------------------------------- */

function drawTopDiscrepanciesPage(doc: jsPDF, report: ReportBundle): void {
  doc.addPage();
  drawRunningHeader(doc, report.clientName);

  let y = drawSectionTitle(
    doc,
    'Top 5 Discrepancies',
    'The five largest variances, ranked by absolute dollar value, with the full calculation trace for each.',
  );

  if (report.topDiscrepancies.length === 0) {
    drawCard(doc, MARGIN.left, y, CONTENT_WIDTH, 22, { fill: C.emerald50, border: C.emerald600 });
    drawText(doc, 'No discrepancies identified', MARGIN.left + 5, y + 9, {
      size: 10,
      bold: true,
      color: C.emerald700,
    });
    drawParagraph(
      doc,
      'Every audited transaction reconciled to the contractual split. The brokerage may still wish to spot-check incoming referral income.',
      MARGIN.left + 5,
      y + 15,
      CONTENT_WIDTH - 10,
      { size: 8.5, lineHeight: 3.8, color: C.slate600 },
    );
    return;
  }

  report.topDiscrepancies.forEach(({ transaction, audit, rank }) => {
    const style = STATUS_STYLE[audit.status];

    const breakdown: Array<[string, string]> = [
      ['Sale price', formatMoney(transaction.salePrice)],
      [
        `Total commission @ ${formatPercent(transaction.commRate)}`,
        formatMoney(audit.totalCommission),
      ],
      [
        `Listing side @ ${formatPercent(transaction.listingSplit)}`,
        formatMoney(audit.listingCommission),
      ],
      [
        `Referral fee out @ ${formatPercent(transaction.referralOut)}`,
        deduct(audit.referralFeeOutAmount),
      ],
      ['Amount after referral', formatMoney(audit.amountAfterReferral)],
      [
        `Brokerage cut @ ${formatPercent(transaction.brokerSplit)}`,
        deduct(audit.brokerageCut),
      ],
      ['Transaction fee', deduct(transaction.transactionFee)],
      ['Expected agent payment', formatMoney(audit.expectedAgentPayment)],
      ['Actual amount paid', formatMoney(transaction.actualPaid)],
    ];

    // Block height estimate: header + 9 rows + discrepancy row + padding.
    const blockHeight = 12 + breakdown.length * 5.2 + 10;
    if (y + blockHeight > CONTENT_BOTTOM) {
      doc.addPage();
      drawRunningHeader(doc, report.clientName);
      y = CONTENT_TOP;
    }

    const headerLabel = `#${rank}   ${transaction.address || '(no address)'}`;
    const statusLabel = `${style.label.toUpperCase()}  ${formatSignedMoney(audit.discrepancy)}`;

    autoTable(doc, {
      startY: y,
      margin: { left: MARGIN.left, right: MARGIN.right, bottom: MARGIN.bottom },
      theme: 'grid',
      styles: {
        font: FONT,
        fontSize: 8,
        cellPadding: 1.8,
        textColor: C.slate700,
        lineColor: C.slate200,
        lineWidth: 0.15,
      },
      head: [[headerLabel, statusLabel]],
      body: breakdown,
      foot: [['Discrepancy (actual - expected)', formatSignedMoney(audit.discrepancy)]],
      headStyles: {
        fillColor: C.slate900,
        textColor: C.white,
        fontStyle: 'bold',
        fontSize: 8.5,
      },
      footStyles: {
        fillColor: style.fill,
        textColor: style.text,
        fontStyle: 'bold',
        fontSize: 8.5,
      },
      columnStyles: {
        0: { cellWidth: CONTENT_WIDTH * 0.66 },
        1: { cellWidth: CONTENT_WIDTH * 0.34, halign: 'right', fontStyle: 'bold', textColor: C.slate900 },
      },
      alternateRowStyles: { fillColor: C.slate50 },
      didParseCell: (data) => {
        // Colour the status cell of the header row (right column only).
        if (data.section === 'head' && data.column.index === 1) {
          data.cell.styles.textColor = style.text;
          data.cell.styles.fillColor = style.fill;
        }
      },
    });

    y = tableFinalY(doc, y) + 7;
  });

  if (report.topDiscrepancies.length < 5) {
    drawParagraph(
      doc,
      `Only ${report.topDiscrepancies.length} discrepant deal${
        report.topDiscrepancies.length === 1 ? ' was' : 's were'
      } identified in this period, so fewer than five entries are shown.`,
      MARGIN.left,
      y,
      CONTENT_WIDTH,
      { size: 8, color: C.slate500 },
    );
  }
}

/* -------------------------------------------------------------------------- */
/*  Page 5 — recommendations                                                  */
/* -------------------------------------------------------------------------- */

function drawRecommendationsPage(doc: jsPDF, report: ReportBundle): void {
  doc.addPage();
  drawRunningHeader(doc, report.clientName);

  let y = drawSectionTitle(
    doc,
    'Recommendations',
    'Specific actions derived from the findings in this report, highest priority first.',
  );

  const severityStyle: Record<string, { accent: Rgb; fill: Rgb; tag: string }> = {
    critical: { accent: C.rose600, fill: C.rose50, tag: 'PRIORITY' },
    warning: { accent: C.amber600, fill: C.amber50, tag: 'REVIEW' },
    info: { accent: C.emerald600, fill: C.emerald50, tag: 'GOOD PRACTICE' },
  };

  report.recommendations.forEach((recommendation, index) => {
    const style = severityStyle[recommendation.severity] ?? severityStyle.info;
    const detailLines = lineCount(doc, recommendation.detail, CONTENT_WIDTH - 24, 8.5);
    const blockHeight = 11 + detailLines * 4.1 + 7;

    if (y + blockHeight > CONTENT_BOTTOM) {
      doc.addPage();
      drawRunningHeader(doc, report.clientName);
      y = CONTENT_TOP;
    }

    drawCard(doc, MARGIN.left, y, CONTENT_WIDTH, blockHeight, {
      fill: C.white,
      border: C.slate200,
    });

    // Number bullet
    setFill(doc, style.accent);
    doc.circle(MARGIN.left + 7, y + 7.5, 3.4, 'F');
    doc.setFont(FONT, 'bold');
    doc.setFontSize(8.5);
    setText(doc, C.white);
    doc.text(String(index + 1), MARGIN.left + 7, y + 8.7, { align: 'center' });

    drawText(doc, recommendation.title, MARGIN.left + 13, y + 8.6, {
      size: 10,
      bold: true,
      color: C.slate900,
      maxWidth: CONTENT_WIDTH - 48,
    });

    // Severity tag
    const tagWidth = measure(doc, style.tag, 6.6, true) + 5;
    setFill(doc, style.fill);
    doc.roundedRect(PAGE_WIDTH - MARGIN.right - 6 - tagWidth, y + 4.5, tagWidth, 5.6, 1.2, 1.2, 'F');
    drawText(doc, style.tag, PAGE_WIDTH - MARGIN.right - 6 - tagWidth / 2, y + 8.4, {
      size: 6.6,
      bold: true,
      color: style.accent,
      align: 'center',
    });

    drawParagraph(doc, recommendation.detail, MARGIN.left + 13, y + 14.5, CONTENT_WIDTH - 24, {
      size: 8.5,
      lineHeight: 4.1,
      color: C.slate600,
    });

    y += blockHeight + 4;
  });

  y += 3;
  if (y < CONTENT_BOTTOM - 16) {
    drawCard(doc, MARGIN.left, y, CONTENT_WIDTH, 15, { fill: C.slate50, border: C.slate200 });
    drawParagraph(
      doc,
      `Prepared by ${report.preparedBy} · ${report.reportDateLabel} · Questions: ${report.contactEmail} · ${report.contactPhone}`,
      MARGIN.left + 5,
      y + 6,
      CONTENT_WIDTH - 10,
      { size: 8, color: C.slate600 },
    );
    drawParagraph(
      doc,
      'This report is confidential and intended only for the named client. Zed Automation is not providing legal, tax or accounting advice.',
      MARGIN.left + 5,
      y + 11,
      CONTENT_WIDTH - 10,
      { size: 7.5, color: C.slate500 },
    );
  }
}

/* -------------------------------------------------------------------------- */
/*  Public API                                                                */
/* -------------------------------------------------------------------------- */

export interface AuditReportResult {
  doc: jsPDF;
  fileName: string;
  report: ReportBundle;
  pageCount: number;
}

/**
 * Build the full multi-page PDF. Pure w.r.t. the DOM (no download), so it can be
 * exercised from Node in tests.
 */
export function buildAuditReportPdf(
  transactions: Transaction[],
  options: ReportOptions,
): AuditReportResult {
  const report = buildReportBundle(transactions, options);
  const doc = new jsPDF({ unit: 'mm', format: 'letter', orientation: 'portrait' });

  doc.setProperties({
    title: `Commission Audit Report — ${report.clientName}`,
    subject: `Commission audit ${report.periodLabel}`,
    author: report.preparedBy,
    creator: 'Zed Automation — Commission Audit & Leakage Detector',
    keywords: 'commission audit, brokerage, leakage, referral fees, Zed Automation',
  });

  drawCoverPage(doc, report);
  drawExecutiveSummaryPage(doc, report);
  drawFindingsPage(doc, report, transactions);
  drawTopDiscrepanciesPage(doc, report);
  drawRecommendationsPage(doc, report);
  drawFooters(doc, report);

  return {
    doc,
    fileName: buildReportFileName(report.clientName, options.reportDate ?? new Date()),
    report,
    pageCount: doc.getNumberOfPages(),
  };
}

/** Build the PDF and trigger a browser download. */
export function downloadAuditReportPdf(
  transactions: Transaction[],
  options: ReportOptions,
): AuditReportResult {
  const result = buildAuditReportPdf(transactions, options);
  result.doc.save(result.fileName);
  return result;
}

/** Raw PDF bytes — used by the verification script and any future e-mail/upload path. */
export function auditReportArrayBuffer(
  transactions: Transaction[],
  options: ReportOptions,
): { buffer: ArrayBuffer; fileName: string; pageCount: number } {
  const result = buildAuditReportPdf(transactions, options);
  return {
    buffer: result.doc.output('arraybuffer') as ArrayBuffer,
    fileName: result.fileName,
    pageCount: result.pageCount,
  };
}

export { buildReportBundle, buildReportFileName };
